export const CHART_CONSTANTS = {
  margin: { top: 60, right: 20, bottom: 30, left: 200 },
  barHeight: 25,
  barPadding: 15,
  groupHeaderHeight: 35,
  avatarSize: 25,
  borderRadius: 12,
  xScalePadding: 10,
  tooltipBgColor: 'rgba(0,0,0,0.8)',
  tooltipTextColor: 'white',
  tooltipPadding: '8px',
  tooltipBorderRadius: '4px',
  tooltipZIndex: 100,
  rowEvenColor: '#f8f8f8',
  rowOddColor: '#ffffff',
  gridLineColor: '#e0e0e0',
  gridLineStrokeWidth: 1,
  gridLineDashArray: '2,2',
  yAxisBorderColor: '#ccc',
  yAxisBorderWidth: 1,
  todayLineColor: '#8A2BE2',
  todayLineStrokeWidth: 2,
  todayLineDashArray: '6,6',
  yLabelFontSize: '0.85rem',
  yLabelFontColor: '#333',
  yLabelBorderBottomColor: '#eee',

  groupHeaderBgColor: '#e0e0e0', 
  groupHeaderFontColor: '#333333',
  groupHeaderFontSize: '14px', 
};